<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
	<Nullable>enable</Nullable>
	
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Supermodel\Persistence\CustomRepos\**" />
    <EmbeddedResource Remove="Supermodel\Persistence\CustomRepos\**" />
    <None Remove="Supermodel\Persistence\CustomRepos\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Frameworks\CsvMaker\CsvMaker.csproj" />
    <ProjectReference Include="..\..\..\Frameworks\Supermodel.Persistence\Supermodel.Persistence.EFCore.SQLite\Supermodel.Persistence.EFCore.SQLite.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.12">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
